package com.gtu.centraltechfest.workshopEntry;

public class WorkshopBenefits {
    public static final String homeautomation_Ben_work;
    public static final String mobilemaking_Ben_work;
    public static final String oracle_Ben_work;
    public static final String tallbuiliding_Ben_work;

    static {
        tallbuiliding_Ben_work = "\u2022\tCertificate of participation to all participants from CIVIL SIMPLIFIED" + System.getProperty("line.separator") + "\u2022\tDevelop good understanding of tall buildings" + System.getProperty("line.separator") + "\u2022\tBetter chances to pursue higher education in IITs/Universities abroad" + System.getProperty("line.separator") + "\u2022\tCan use this experience to develop good B.Tech/M.Tech projects" + System.getProperty("line.separator") + "\u2022\tPost-workshop material and references for detailed information on topic" + System.getProperty("line.separator") + "\u2022\tOpportunity to interact with experts to discuss career options";
        mobilemaking_Ben_work = "\u2022\tThe students will be receiving participation certificates from the HELIOS committee with IIT-BOMBAY" + System.getProperty("line.separator") + "\u2022\tThe students will also be getting a chance to represent in the finals at IIT-BOMBAY scheduled on 4-5thApril" + System.getProperty("line.separator") + "\u2022\tEach student will be receiving a mobile making Kit and also students will also be receiving full knowledge on the making of a mobile which will help in future" + System.getProperty("line.separator") + "\u2022\tKnowledge on mobile making will help them in placement and will be adding a great value to their resume ";
        homeautomation_Ben_work = "\u2022\tCertificate of Participation to all Participants from ROBOTR!X INDIA." + System.getProperty("line.separator") + "\u2022\tFree Comprehensive course study material (Handouts) will be provided to participants." + System.getProperty("line.separator") + "\u2022\t1 Take Away Robotic Kit will be provided to the groups (each having 4 students)." + System.getProperty("line.separator") + "\u2022\tBetter chances to pursue higher education in IITs/Universities abroad." + System.getProperty("line.separator") + "\u2022\tCan use this experience to develop good B.Tech/M.Tech projects." + System.getProperty("line.separator") + "\u2022\tPost-workshop material and references for detailed information on topic" + System.getProperty("line.separator") + "\u2022\tOpportunity to interact with experts to discuss career options.";
        oracle_Ben_work = "\u2022\tCertificate of participation to all participants from ORACLE." + System.getProperty("line.separator") + "\u2022\tDevelop good understanding of GREENFOOT." + System.getProperty("line.separator") + "\u2022\tBetter chances to pursue higher education in IITs/Universities abroad." + System.getProperty("line.separator") + "\u2022\tCan use this experience to develop good B.Tech/M.Tech projects." + System.getProperty("line.separator") + "\u2022\tPost-workshop material and references for detailed information on topic" + System.getProperty("line.separator") + "\u2022\tOpportunity to interact with experts to discuss career options.";
    }
}
