package com.gtu.centraltechfest.workshopEntry;

public class WorkshopContent {
    public static final String home_course_work;
    public static final String mobilemaking_course_work;
    public static final String oracle_course_work;
    public static final String tallbuilding_course_work;

    static {
        tallbuilding_course_work = "\u2022\tIntroduction to tall building systems" + System.getProperty("line.separator") + "\u2022\tTheory of load resisting systems" + System.getProperty("line.separator") + "\u2022\tIndustrial approach to projects" + System.getProperty("line.separator") + "\u2022\tUnderstanding the different load acting on a structure." + System.getProperty("line.separator") + "\u2022\tWind force calculations using Indian Standard Code" + System.getProperty("line.separator") + "\u2022\tCase studies from real industry for better understanding the design of Tall building" + System.getProperty("line.separator") + "\u2022\tModeling and analyzing the structure on CAD based software." + System.getProperty("line.separator") + "\u2022\tDesigning the various structural components to create a safe Tall structure in CAD based Software." + System.getProperty("line.separator") + "\u2022\tLive Demonstration and practical examples." + System.getProperty("line.separator") + "\u2022\tEvaluation of different problem statements.";
        oracle_course_work = "\u2022\tGetting Started With Greennfoot " + System.getProperty("line.separator") + "\u2022\tUsing Methods, Variables and Parameters " + System.getProperty("line.separator") + "\u2022\tWorking with Source Code and Documentation " + System.getProperty("line.separator") + "\u2022\tDeveloping and Testing an Application " + System.getProperty("line.separator") + "\u2022\tUsing Randomization and Understanding Dot Notation and Constructors " + System.getProperty("line.separator") + "\u2022\tDefining Methods " + System.getProperty("line.separator") + "\u2022\tUsing Sound and Keyboard Control " + System.getProperty("line.separator") + "\u2022\tCreating a World, Animating Actors, and Ending a Game " + System.getProperty("line.separator") + "\u2022\tUnderstanding Abstraction " + System.getProperty("line.separator") + "\u2022\tUsing Loops, Variables, and Strings " + System.getProperty("line.separator") + "\u2022\tPutting it All Together with Greenfoot.";
        mobilemaking_course_work = "\u2022\tIntroduction to Embedded System and Robotics" + System.getProperty("line.separator") + "\u2022\tLCD and Keypad Interfacing" + System.getProperty("line.separator") + "\u2022\tCommunication" + System.getProperty("line.separator") + "\u2022\tGSM Modem Interfacing" + System.getProperty("line.separator") + "\u2022\tMaking of Mobile";
        home_course_work = "\u2022\tIntroduction of Robotics." + System.getProperty("line.separator") + "\u2022\tIntroduction to Switches." + System.getProperty("line.separator") + "\u2022\tIntroduction to Home Automation." + System.getProperty("line.separator") + "\u2022\tIntroduction to Arduino Board &amp; Software. " + System.getProperty("line.separator") + "\u2022\tIntroduction to Bluetooth module HC-05." + System.getProperty("line.separator") + "\u2022\tIntroduction of DTMF Technology." + System.getProperty("line.separator") + "\u2022\tLearning of Processing C Language. " + System.getProperty("line.separator") + "\u2022\tProgramming of Home Automation System. " + System.getProperty("line.separator") + "\u2022\tAnatomy of Complete Home Automation Systems.";
    }
}
