package com.gtu.centralfest.staticentry;

public class EventProblem {
    public static final String ace_of_empire_prostate;
    public static final String algo_wizards_prostate;
    public static final String auto_dexterous_prostate = "Participants are supposed to make propelling vehicle from things given to them in the first round. The shortlisted teams from the first round will go for second round. In the second round, kit will be provided to them and they are supposed to make an automobile model based on theme given to them. The shortlisted team from second round will go to the third round. In the third round they are supposed to give description of their idea behind the model.";
    public static final String beat_the_around_loom_prostate;
    public static final String biz_plan_prostate;
    public static final String bridge_it_prostate;
    public static final String cad_maestro_prostate;
    public static final String chem_e_car_prostate = "To design and construct a car that is powered with a chemical energy source that will carry a specified load (i.e. given 400 ml of water) over a given distance and can also stop when needed i.e. be accurate.";
    public static final String chemo_freeze_prostate = "To design and construct a working model that can cool down the hot water via conduction showing your dexterity level and technical competency.";
    public static final String code_square_prostate;
    public static final String crackit_prostate = "The fantasies of people seeing the actors stealing the precious things, so helping the people live their fantasies of actually experiencing the treat of stealing the unstealables. So come steal it and live the best of your fantasy to steal.";
    public static final String electrotrade_Desc = "Technology in a business is growing concern. Business always needs technology to sustain. The same problem happens with technology if it will not be embedded with proper managerial skills. So, success in business lies within technology implemented. Technology amalgamated with entrepreneur skill will become vehicle that facilitates the prosperity in life of any individual, firm and nation as a whole.  ";
    public static final String estidio_de_case_prostate = "Prior to the event, the topics of case studies will be provided to the participants. They\u2019ll have to analyze, scrutinize and prepare the full detailed case study of the content. The participants will have to present it in the form of a presentation in the first round. In the second round, a group discussion regarding various managerial concepts will take place.  Based on the over-all performance of the teams, results will be declared.";
    public static final String file_savvy_prostate;
    public static final String food_factory_prostate = "You a worker in a food factory and your boss assigned you to collect raw materials for preparing the food from the available resources in the factory. Hence, you have to use the machinery of factory and get the job done. Your objective is to make a robust robot that can have a gripper or any kind of mechanism that can slide or carry the block of particular size. ";
    public static final String galaxy_runner_prostate;
    public static final String goldberg_prostate;
    public static final String green_soul_prostate;
    public static final String junkyard_wars_prostate = "Participants will be tested for their ability to make use of every resource available in an optimized manner under the given time constraint. The participants will have to apply innovative ideas and feasible solutions of the given real life problems to design the mechanism from the given scrap and have to complete the task in required time limit.";
    public static final String kick_n_climb_prostate;
    public static final String make_ur_way_prostate = "Participants will be given sheet marked with different points representing school, hospital, lake, mall, police station and such other places. Participants will be required to prepare a model connecting these points by using mass transport systems like bus services, metro, etc.";
    public static final String maquet_tex_prostate = "Participants have to prepare a Working or static Model with proper Explanations.";
    public static final String moon_mission_prostate;
    public static final String questography_prostate;
    public static final String retro_inginerie_prostate;
    public static final String robo_prostate = " ";
    public static final String robowars_prostate;
    public static final String roverrun_prostate = "Build a robust manual robot that can go through the rocky rough terrain, can beat the water, oil hurdles, accept the challenge, encounter the obstacles such as slippery surfaces, bridges, slopes, etc. and reach the top in minimum amount of time.";
    public static final String smile_prostate;
    public static final String stasmp_prostate;
    public static final String styloelectra_prostate = " The rising tide of wearables, the usability and attraction are the heart of the event. So invent it and design it to the best of your abilities making it a fascinating and exploitable innovation.";
    public static final String technathon_Desc = "    ";
    public static final String thoxophilite_prostate = "Participants have to design a crossbow using any convenient mechanism and have to demonstrate the accuracy of their crossbow. Prior to that, participants have to design a very simple mechanism asked on the spot to continue further. The sample mechanism will be showed at the time of event and other specifications will be announced.";
    public static final String un_debate_prostate;
    public static final String urbanista_prostate;
    public static final String water_roadies_prostate = "Participants have to design a water filter satisfying the parameters associated with it like retention time, hydraulic gradient, etc. The design must be economic and filter to be developed must be efficient.";
    public static final String wolf_of_wallstreet_prostate = "Show your investment skills and be the Wolf of the Wall Street by investing virtual money. Whether you\u2019re new to the stock markets or an experienced investor, this is a powerful tool for building skill, evaluating and tuning your strategy, and gaining important investing experience. The objective is to maximize this amount by intelligently and smartly investing in the Stock Market. Trade, learn and compete with the best!";

    static {
        goldberg_prostate = "Show your skills on constructing your own Goldberg\u2019s Mechanism performing some simple task with reasonable complexity and prove your mechanical dexterity. Every team has to perform only one task. Completion of task gives 70 marks to team. From starting to end, any type of energy conversions can be done, but at the end one of the contraption, selected task have to be completed by team to gain the task completion points. Task must be performed at the end of the contraption. Completion of task during the contraption will not be considered." + System.getProperty("line.separator") + "One of the following tasks have to be performed by a participated team" + System.getProperty("line.separator") + System.getProperty("line.separator") + "Illuminating the bulb (without electricity)" + System.getProperty("line.separator") + "Raising the flag (LDCE-GTU TECHFEST-2015)" + System.getProperty("line.separator") + "Ringing the bell (any type of the siren or ring)" + System.getProperty("line.separator") + "Above all Mechanism must be created by yourself before coming here ,You just have Set-up whole mechanism here";
        retro_inginerie_prostate = "\u2022\tTo investigate a disaster scene and deduce" + System.getProperty("line.separator") + "\u2022\tAll the possible faults that may cause the disaster." + System.getProperty("line.separator") + "\u2022\tAll the possible causes that have caused the disaster." + System.getProperty("line.separator") + System.getProperty("line.separator") + " Above things is to be done by giving proper presentation" + System.getProperty("line.separator") + System.getProperty("line.separator") + "\u2022\tIf your team is competent enough to clear the first round, you will be asked to prepare a working model of an instrument based on an idea and using the stationary provided in the allotted time period.";
        urbanista_prostate = "Round 1: A particular building will be allotted to each group of participants. They have to carry out a brief survey of that building for the 45 minutes and then they have to prepare a proper line diagram (only plan) of that building in an hour." + System.getProperty("line.separator") + System.getProperty("line.separator") + "Round 2: A task of town planning will be given to the participants along with the data. Participants have to prepare a model of town satisfying the given data.";
        bridge_it_prostate = "Round 1: To construct a cable-stayed bridge on the spot using provided materials and specified dimensions for moving load conditions." + System.getProperty("line.separator") + System.getProperty("line.separator") + "Round 2: To construct a structural member from the given drawing and as per given specifications.";
        smile_prostate = "The participant will be given a defined area which he will be required to convert it to an Eco friendly zone. The major topics to be included are:-" + System.getProperty("line.separator") + "\u2022\tWaste Management" + System.getProperty("line.separator") + "\u2022\tMunicipal Engineering" + System.getProperty("line.separator") + "\u2022\tEnergy Conservation " + System.getProperty("line.separator") + "\u2022\tCleaner Production" + System.getProperty("line.separator") + "\u2022\tWater Conservation and such similar topics." + System.getProperty("line.separator") + System.getProperty("line.separator") + "Proper explanation will be required for each solution suggested";
        green_soul_prostate = "Design a model for a better TOMORROW." + System.getProperty("line.separator") + "\u2022Models should be based on the following topics:" + System.getProperty("line.separator") + "\u2022\tZero discharge" + System.getProperty("line.separator") + "\u2022\tZero waste" + System.getProperty("line.separator") + "\u2022\tTotal waste management" + System.getProperty("line.separator") + "\u2022\tGreen technologies" + System.getProperty("line.separator") + "\u2022\tEnergy conservation";
        un_debate_prostate = "The participants will be assigned a specific country and they will participate in the event as the delegate representing their given country on the international model platform." + System.getProperty("line.separator") + "They will be taking the stance of their country on the given agenda." + System.getProperty("line.separator") + "The participants must stick to their country\u2019s foreign policy." + System.getProperty("line.separator") + "They must not use abusive or rude language." + System.getProperty("line.separator") + "The participants must be dressed in formal clothes." + System.getProperty("line.separator") + "The event will consist of an opening statement, a roll call and sessions of moderated (formal) and unmoderated(informal) caucuses(debate).";
        biz_plan_prostate = "Whiz-a-Biz is typically an event that judges a B-Plan on various parameters be it viability, opportunity, strategizing, forecasting, etc. On the way, it would check the equanimity of an individual by testing his/her Decision Making skill, as this skill is crucial for any business to proliferate.." + System.getProperty("line.separator") + "Prepare a business plan of a fictional product representing the necessary details and decisions needed for the inception and expansion of your business which if qualified for the next round, you will be required to provide a presentation of your business plan.";
        ace_of_empire_prostate = "With the available resources buy a proper city, bid on necessary items needed, impress the investors and make progress to make your city prosperous." + System.getProperty("line.separator") + "\u2022Round 1: Elimination round. Rules will be announced on the spot. Total of 30 teams will qualify for round2." + System.getProperty("line.separator") + System.getProperty("line.separator") + "\u2022Round 2:  Each team that qualifies will be given a fixed amount of virtual money. With that will start the auction. There will be various cities to choose from and bid on with different prices depending on the location and area of the city. After that there will be an auction for the items that are needed in a city (such as residential complex, hospitals, marts, etc) prices of which would again differ from each other. After this round a break will be given to the participants." + System.getProperty("line.separator") + "\u2022While this round would be going on there would be lots of investors around observing your team. They will be investing on your city during the break." + System.getProperty("line.separator") + System.getProperty("line.separator") + "\u2022Round 3: After the break each team will be informed about the investments on them. They will now be allowed to upgrade the items of their city by switching to a better class of items. In the end the team that would have established the most prosperous and well planned city will be declared as the winner by the judge(s). ";
        cad_maestro_prostate = "Participants will be given some design tasks, which shall be completed by using AutoCAD software. The task will require basic knowledge of AutoCAD, and your design skills." + System.getProperty("line.separator") + "Round 1: Drafting skills" + System.getProperty("line.separator") + "Round 2: Object creation" + System.getProperty("line.separator") + "Round 3: Solid Modeling";
        galaxy_runner_prostate = "Construct a bot capable of following the line using sensors in the least possible time. The event will be conducted in 2 rounds:" + System.getProperty("line.separator") + System.getProperty("line.separator") + "ROUND 1 (QUALIFYING ROUND) :" + System.getProperty("line.separator") + "The robot should cross the junctions and reach the end point without deviating from the line. Each time the robot deviates from its path penalty will be given to the team. When the robot deviates at the 8th time from track, it will be disqualified. Magnitude of the penalty time is decided on the day of the event." + System.getProperty("line.separator") + "Bonus points will be awarded to the robot if it automatically stops at the halt" + System.getProperty("line.separator") + "Extra points will be awarded for covering check points." + System.getProperty("line.separator") + "In this round, repetition of any checkpoint will not be considered." + System.getProperty("line.separator") + "Every RESTART is taken from previous check point." + System.getProperty("line.separator") + System.getProperty("line.separator") + "ROUND-2 (FINAL ROUND) :" + System.getProperty("line.separator") + "The track for final round will be revealed only to those who would clear the qualifying round." + System.getProperty("line.separator") + "In this round the whole path will be considered and after the 5th checkpoint, there will be 2 paths for the robot. If path 1 will be selected then the robot will go in the reverse direction up to the end or if path 2 will be selected then the robot will go in forward direction." + System.getProperty("line.separator") + "Every RESTART is taken from previous check point.";
        robowars_prostate = "Design your own bot aimed to destroy the rival\u2019s bot. Your bot should be able to Grab or Drag the PAHELWAN(object similar to a ball)  to goal post line(similar to Rugby). BOT should be in physical contact with PAHELWAN while crossing goal line which is before the goal post." + System.getProperty("line.separator") + "\u2022\tPAHELWAN Specifications:" + System.getProperty("line.separator") + "\u2022\tDiameter: Maximum 30 cm." + System.getProperty("line.separator") + "\u2022\tWeight: Between 8 kg and 20 kg.";
        moon_mission_prostate = "\u2022\tBot has to climb a slant wall with the help of rope while facing obstacles in 1st round" + System.getProperty("line.separator") + "\u2022\tBot has to pull an object attached to rope from the top position in 2nd round.";
        algo_wizards_prostate = "\u2022Round 1: Be a Wizard or a Muggle??" + System.getProperty("line.separator") + "  This round will be conducted in two phases. Phase 1 \u2013 \u201cTicket for Platform 93/4\u201d - will be of 10 minutes consisting of 20 questions. Phase 2 - \u201cJourney to Hogwarts\u201d - will be of 45 minutes consisting of MCQs and numeric questions based on the concepts of Data Structure and Algorithms. There will be 12 main questions each with one sub-question. The main question would be the normal one and if that has been answered by the participant then only sub-question will be unlocked which would be related to main question but tricky one." + System.getProperty("line.separator") + System.getProperty("line.separator") + "\u2022Round 2:" + System.getProperty("line.separator") + "  No journey is without hurdles and so is this. You will face the hurdles now onwards. Each iteration will be of 15 minutes.\t" + System.getProperty("line.separator") + "  \u2022Iteration 1: The Sorcerer\u2019s Stone" + System.getProperty("line.separator") + "   This would consist of clues to the data structures that they need to identify." + System.getProperty("line.separator") + "  \u2022Iteration 2: The Chamber of Secrets" + System.getProperty("line.separator") + "   This would contain short story and question based on that." + System.getProperty("line.separator") + "  \u2022Iteration 3: The Prisoner of Azkaban" + System.getProperty("line.separator") + "   This would consist of some simple examples of data structures." + System.getProperty("line.separator") + "  \u2022Iteration 4: The Goblet of Fire" + System.getProperty("line.separator") + "   This would contain searching based concepts. Quidditch and Triwizard game scenario will be used in the iteration. After finding correct algorithm participants need to code the algorithm." + System.getProperty("line.separator") + System.getProperty("line.separator") + "\u2022Round 3:" + System.getProperty("line.separator") + "   The journey continues\u2026" + System.getProperty("line.separator") + "  \u2022Iteration 5: The Order of Phoenix" + System.getProperty("line.separator") + "   Here the participants need to apply their brains to solve the given problem and need to come up with the optimal solution." + System.getProperty("line.separator") + "  \u2022Iteration 6: The Half-Blood Prince" + System.getProperty("line.separator") + "  \u2022Iteration 7: The Deathly Hallows" + System.getProperty("line.separator") + "   These would contain question based on the scenario that Harry is in search of Horcruxes. Tricky and complex coding is to be done." + System.getProperty("line.separator") + "   Each iteration will be of 20 minutes and it would contain real life problems on data structure and algorithms.";
        code_square_prostate = "Code Square, an online coding competition where coders will be given various problems based on data structure and algorithmic concepts and the participants will have to solve them and give the code as well as the output file." + System.getProperty("line.separator") + "The problem will contain some fictional scenarios where you would apply and implement your conceptual knowledge and coding skills to crack the problem. There will be other coders who will be simultaneously solving the same problems and competing with you. So the key to win is speed and accuracy.";
        file_savvy_prostate = "\u2022Round 1: Participants will be provided with simple questions based on I/O and sql. Participants have to find the answer in the grid of the alphabets prepared for each question." + System.getProperty("line.separator") + System.getProperty("line.separator") + "\u2022Round 2: Participants, having cleared the first round, will be provided with sql queries not in proper order.These queries will create more than one table. Participants will have to analyze these queries and predict the tables those are supposed to be generated. After that, they will be provided with tasks related to the retrieval of some data from the generated tables. Queries for these tasks should be in a text file generated using file I/O programming." + System.getProperty("line.separator") + System.getProperty("line.separator") + "\u2022Round 3: This round will be on 28th of March, 2015 in which participants have to prepare a java program that reads input from one \u201c.txt\u201d file , perform some computations on that input and generate a new file containing the required output.";
        kick_n_climb_prostate = "\u2022Round 1: A 10x10 snake and ladder board will be displayed on the computer screen with timer. A button will be present on the screen named 'Roll dice', which on pressing, generates a random number between 1 and 6 playing the role of dice. The marker will move forward by the number of steps equivalent to the number on the dice. If the marker encounters the ladder, a question will pop up. Submitting the correct answer, the marker will climb the ladder else would remain stagnant till the next turn. Same goes for the encounter with snakes. " + System.getProperty("line.separator") + "If the question is answered correctly, the marker will hold its position otherwise it would be forced to come down to the square consisting the tail of that snake. Moreover, there will be some special squares also containing questions, which, if answered correctly, would lead the marker move forward double times the number generated by the 'Roll Dice'. Relative score will also be calculated on the basis of frequency of correct answers of the questions encountered by them. The one who reaches the 100th square in minimum time and maximum score  will be qualified for the next round." + System.getProperty("line.separator") + System.getProperty("line.separator") + "\u2022Round 2: The basic structure of the competition would be similar to that of a typical soccer game. 10 players chosen randomly would form a team and two teams compete against each other. Scores increment with correctly answered question depending on who answers it first. The game would implement the typical soccer game events, such as dribbling, passing, tackling and goal scoring. The penultimate round has been formed as a typical penalty shoot-out between two teams of five players each. To ensure uniformity, the teams are formed at random for each level.";
        questography_prostate = "Basic knowledge of C is required to solve the problems and to find the clues leading you to the next step. The event will be conducted in three rounds." + System.getProperty("line.separator") + "\u2022\tRound 1: BUG\u00adA\u00adTHON\u00ad Participants will be provided with the bugs which are to be solved on which their leader board ranking and their allies and enemies will also be decided. Public key for all teams will be given." + System.getProperty("line.separator") + System.getProperty("line.separator") + "\u2022\tRound 2: This round will have 4 zones where each team will have to finish three zones to finish the round. In each zone, participants will be given different clues, riddles, puzzles, etc. which will lead them to their key to next zone. Also, each team will know their allies and enemies as they solve clues. If a team goes to wrong zone or exceed time limit will be given penalty in form of Bazinga." + System.getProperty("line.separator") + System.getProperty("line.separator") + "\u2022 Round 3: Itis similar to round 2 with a more tough competition and one zone would be a knock out zone which will allow only half of the teams to proceed to next zone.";
        beat_the_around_loom_prostate = "A textile based event related to weaving on conventional handloom. The participants have to weavethe design on the loom according to the design structure made by them on the point paper. The participants will be judge on the basis of precision of design on the fabric and the quality of the fabric design (i.e) its compactness the fabric appearance and the neatness of their work." + System.getProperty("line.separator") + "      Participants have to weave fabric on handloom with maximum speed and accuracy in given interval of time. Also they have to decorate it with the given material.\t" + System.getProperty("line.separator") + System.getProperty("line.separator") + " Round 1" + System.getProperty("line.separator") + "1.\t The design for the first round would be made by participants by themselves and time limit for the round 1 will be 30 minutes." + System.getProperty("line.separator") + "2.\tThe 6 team shortlisted will be participating in the second round where the participants will have to select the design from the cheats placed in the bowl." + System.getProperty("line.separator") + "3.\tTime for the task will be  30 minutes." + System.getProperty("line.separator") + "4.\tThe design for the round one would be prepared by the team itself." + System.getProperty("line.separator") + System.getProperty("line.separator") + " Round 2" + System.getProperty("line.separator") + "1.\tThe time for the task will be 45 minutes." + System.getProperty("line.separator") + "2.\tThe different types of weft would be provided." + System.getProperty("line.separator") + "3.\tWeft would be different colouring yarns, waste of fabrics, roving  , slivers, and many more." + System.getProperty("line.separator") + "4.\tParticipants have to prepare fabric using this all material." + System.getProperty("line.separator") + "5.\tThe judging Criteria will remain same for round 2.";
        stasmp_prostate = new StringBuilder(EventDescClass.stasmp_Desc).append(System.getProperty("line.separator")).append(System.getProperty("line.separator")).append("\tRound one").append(System.getProperty("line.separator")).append("1.\tIn round one the team would be provided with 3 blocks and time duration will be 45 minutes.").append(System.getProperty("line.separator")).append("2.\tHalf meter cloth will be provided per team.").append(System.getProperty("line.separator")).append("3.\tFrom round one 6 teams will be shortlisted  for round 2.").append(System.getProperty("line.separator")).append("4.\tDyes for printing would be provided by the techfest team itself. ").append(System.getProperty("line.separator")).append(System.getProperty("line.separator")).append("  Round Two").append(System.getProperty("line.separator")).append("1.\tIn second round participants will be 3 blocks and 3 Vegetables for printing the fabric.").append(System.getProperty("line.separator")).append("2.\tThe time will be 1 hour for Second round. No extra time will be given.").append(System.getProperty("line.separator")).append("3.\tThe Participants will be judged on the basis of their Creativity and Perfection.").append(System.getProperty("line.separator")).append("4.\tRules and regulations for the second round will remain same.").toString();
    }
}
